dbt_training:
  outputs:
    dev:
      account: yl45797.east-us-2.azure
      database: analytics_046
      password: "{{ env_var('DBT_PASSWORD') }}"
      role: developer_046
      schema: dbt_jmourlam
      threads: 1
      type: snowflake
      user: student046
      warehouse: developer_wh_046
    prod:
      account: yl45797.east-us-2.azure
      database: analytics_046
      password: "{{ env_var('DBT_PASSWORD') }}"
      role: developer_046
      schema: dbt_prod
      threads: 1
      type: snowflake
      user: student046
      warehouse: developer_wh_046
  target: dev
